### ISSUE TITLE
Need to Build on new 6.11.1 Kernel

### ISSUE THREAD

**Issue by shedowe19** [zabbly/zfs#4]
This Packages are not anymore compatibility with the new Kernel 6.11.1

**Comment by shedowe19** [comment]
```
DKMS make.log for zfs-2.2.5-amd64-202408071635 for kernel 6.11.1-1-liquorix-amd64 (x86_64)
Mi 2. Okt 12:55:22 CEST 2024
make  all-recursive
make[1]: Verzeichnis „/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build“ wird betreten
Making all in module
make[2]: Verzeichnis „/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module“ wird betreten
mkdir -p os/linux/spl/
mkdir -p avl/ icp/ icp/algs/aes/ icp/algs/blake3/ icp/algs/edonr/ icp/algs/modes/ icp/algs/sha2/ icp/algs/skein/ icp/api/ icp/asm-aarch64/blake3/ icp/asm-aarch64/sha2/ icp/asm-arm/sha2/ icp/asm-ppc64/blake3/ icp/asm-ppc64/sha2/ icp/asm-x86_64/aes/ icp/asm-x86_64/blake3/ icp/asm-x>
make -C /lib/modules/6.11.1-1-liquorix-amd64/build  \
          \
        M="$PWD"  CONFIG_ZFS=m modules
make[3]: Verzeichnis „/usr/src/linux-headers-6.11.1-1-liquorix-amd64“ wird betreten
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-condvar.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-cred.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-err.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-generic.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-kstat.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-procfs-list.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-shrinker.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-thread.o
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-trace.o
In file included from /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/spl/sys/uio.h:31,
                 from /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/spl/sys/sunddi.h:28,
                 from /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-generic.c:42:
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/kernel/linux/blkdev_compat.h: In function ‘blk_queue_set_write_cache’:
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/kernel/linux/blkdev_compat.h:93:2: error: #error "Unsupported kernel"
   93 | #error "Unsupported kernel"
      |  ^~~~~
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/kernel/linux/blkdev_compat.h: In function ‘blk_queue_set_read_ahead’:
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/include/os/linux/kernel/linux/blkdev_compat.h:105:10: error: ‘struct request_queue’ has no member named ‘backing_dev_info’
  105 |         q->backing_dev_info.ra_pages = ra_pages;
      |          ^~
  CC [M]  /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-tsd.o
make[5]: *** [scripts/Makefile.build:244: /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-generic.o] Fehler 1
make[5]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:585:35: error: initialization of ‘int (*)(const struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(const struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} fro>
  585 |                 .proc_handler   = &proc_doslab,
      |                                   ^
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:585:35: note: (near initialization for ‘spl_kmem_table[0].proc_handler’)
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:594:35: error: initialization of ‘int (*)(const struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(const struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} fro>
  594 |                 .proc_handler   = &proc_doslab,
      |                                   ^
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:594:35: note: (near initialization for ‘spl_kmem_table[1].proc_handler’)
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:603:35: error: initialization of ‘int (*)(const struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(const struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} fro>
  603 |                 .proc_handler   = &proc_doslab,
      |                                   ^
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:603:35: note: (near initialization for ‘spl_kmem_table[2].proc_handler’)
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:629:35: error: initialization of ‘int (*)(const struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(const struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} fro>
  629 |                 .proc_handler   = &proc_dohostid,
      |                                   ^
/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.c:629:35: note: (near initialization for ‘spl_table[1].proc_handler’)
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:244: /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module/os/linux/spl/spl-proc.o] Fehler 1
make[4]: *** [/usr/src/linux-headers-6.11.1-1-liquorix-amd64/Makefile:1937: /var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module] Fehler 2
make[3]: *** [Makefile:224: __sub-make] Fehler 2
make[3]: Verzeichnis „/usr/src/linux-headers-6.11.1-1-liquorix-amd64“ wird verlassen
make[2]: *** [Makefile:56: modules-Linux] Fehler 2
make[2]: Verzeichnis „/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build/module“ wird verlassen
make[1]: *** [Makefile:973: all-recursive] Fehler 1
make[1]: Verzeichnis „/var/lib/dkms/zfs/2.2.5-amd64-202408071635/build“ wird verlassen
make: *** [Makefile:877: all] Fehler 2
```

**Comment by stgraber** [comment]
That's normal. I only do the work to get the ZFS packages working on a newer kernel when I switch zabbly/linux to that new kernel. 

Currently zabbly/linux is on 6.10.11 so I don't need the ZFS packages to work on 6.11 yet.

**Comment by stgraber** [comment]
Forgot to close that, this has now been fixed for a little while.
